/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Footer: React.FC = () => {
  return (
    <footer className="flex flex-wrap gap-5 mt-52 w-full rounded-none max-md:mt-10 max-md:max-w-full">
      <div className="flex flex-col items-start text-lg font-bold leading-8 text-white">
        <div className="flex text-3xl tracking-wide text-white capitalize whitespace-nowrap">
          <div className="grow">M</div>
          <div>N</div>
          <div>T</div>
          <div>N</div>
        </div>
        <div className="mt-8">
          Get out there & discover your next slope, mountain & destination!
        </div>
        <div className="self-stretch mt-32 font-medium max-md:mt-10">
          Copyright 2023 MNTN, Inc. Terms & Privacy
        </div>
      </div>
      <div className="flex-auto max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <div className="flex flex-col w-[55%] max-md:ml-0 max-md:w-full">
            <nav className="flex flex-col grow items-start text-lg font-medium leading-8 text-white max-md:mt-10">
              <h3 className="self-stretch text-2xl font-bold leading-none text-amber-200">
                More on The Blog
              </h3>
              <a href="#about" className="mt-6">
                About MNTN
              </a>
              <a
                href="#contributors"
                className="self-stretch mt-4 max-md:mr-2.5"
              >
                Contributors & Writers
              </a>
              <a href="#write" className="mt-4">
                Write For Us
              </a>
              <a href="#contact" className="mt-4">
                Contact Us
              </a>
              <a href="#privacy" className="mt-4">
                Privacy Policy
              </a>
            </nav>
          </div>
          <div className="flex flex-col ml-5 w-[45%] max-md:ml-0 max-md:w-full">
            <nav className="flex flex-col items-start text-lg font-medium leading-8 text-white max-md:mt-10">
              <h3 className="self-stretch text-2xl font-bold leading-none text-amber-200">
                More on MNTN
              </h3>
              <a href="#team" className="mt-6">
                The Team
              </a>
              <a href="#jobs" className="mt-4">
                Jobs
              </a>
              <a href="#press" className="mt-4">
                Press
              </a>
            </nav>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
