/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Header: React.FC = () => {
  return (
    <header className="flex relative flex-col px-20 pt-16 w-full min-h-[1113px] pb-[516px] max-md:px-5 max-md:pb-24 max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/42010234b6b9a2a427ae1f480f9c3439dab4c56c6074ca69d635627067859a62?apiKey=3d455ab335804543820e9aded0b16cbd&"
        alt=""
        className="object-cover absolute inset-0 size-full"
      />
      <nav className="flex relative flex-wrap gap-5 justify-between items-start w-full font-bold text-white max-md:max-w-full">
        <div className="flex shrink-0 h-6 w-[108px]" />
        <div className="flex gap-5 justify-between self-stretch my-auto text-lg">
          <a href="#equipment">Equipment</a>
          <a href="#about">About us</a>
          <a href="#blog">Blog</a>
        </div>
        <div className="flex gap-2 text-lg whitespace-nowrap">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/4cb2434cf346671b881fa34f8b7e7904aa25fe763344a588ad2959e2859b3d63?apiKey=3d455ab335804543820e9aded0b16cbd&"
            alt=""
            className="object-contain shrink-0 w-6 aspect-square"
          />
          <a href="#account">Account</a>
        </div>
      </nav>
      <div className="flex relative flex-wrap gap-5 justify-between items-center mt-48 mr-9 mb-0 w-full text-lg max-w-[1725px] max-md:mt-10 max-md:mr-2.5 max-md:mb-2.5 max-md:max-w-full">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/9a3961243028baa1232e3f3d8944ce28cf3cdb75a80ed8304e8021b0036675cd?apiKey=3d455ab335804543820e9aded0b16cbd&"
          alt=""
          className="object-contain shrink-0 self-stretch my-auto w-6 aspect-[0.14]"
        />
        <div className="flex overflow-hidden flex-col items-start self-stretch max-md:max-w-full">
          <div className="flex gap-5 max-w-full font-extrabold text-amber-200 uppercase tracking-[6px] w-[316px]">
            <div className="flex shrink-0 my-auto h-0.5 bg-amber-200 w-[72px]" />
            <div className="flex-auto">A Hiking guide</div>
          </div>
          <h1 className="self-stretch mt-8 text-8xl font-semibold text-white capitalize leading-[100px] max-md:max-w-full max-md:text-4xl max-md:leading-[51px]">
            Be prepared for the Mountains and beyond!
          </h1>
          <div className="flex gap-4 mt-8 max-w-full font-bold text-white w-[126px]">
            <div>scroll down</div>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/a95504f7cd89c9b9fe763d76a610ec10afaf157490b11fede173a4ec9649a2e5?apiKey=3d455ab335804543820e9aded0b16cbd&"
              alt=""
              className="object-contain shrink-0 w-4 aspect-[0.67]"
            />
          </div>
        </div>
        <div className="flex overflow-hidden flex-col items-end self-stretch my-auto font-bold text-right text-white whitespace-nowrap">
          <div>Start</div>
          <div className="mt-10">01</div>
          <div className="mt-10">02</div>
          <div className="mt-10">03</div>
        </div>
      </div>
    </header>
  );
};

export default Header;
