/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header.tsx";
import HikingSection from "./HikingSection.tsx";
import Footer from "./Footer.tsx";

const HikingGuide: React.FC = () => {
  return (
    <div className="flex overflow-hidden flex-col pb-32 bg-gray-900 shadow-2xl max-md:pb-24">
      <div className="flex flex-col pb-20 w-full max-md:max-w-full">
        <Header />
        <main className="flex overflow-hidden flex-col items-center self-center mt-60 w-full max-w-[1462px] max-md:mt-10 max-md:max-w-full">
          <HikingSection
            number="01"
            title="What level of hiker are you?"
            subtitle="GEt Started"
            content="Determining what level of hiker you are can be an important tool when planning future hikes. This hiking level guide will help you plan hikes according to different hike ratings set by various websites like All Trails and Modern Hiker. What type of hiker are you – novice, moderate, advanced moderate, expert, or expert backpacker?"
            imageSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/f8081f16530b368a771acf0182e7c8248e669ef6676393a55b1be6c47f2b7d36?apiKey=3d455ab335804543820e9aded0b16cbd&"
          />
          <HikingSection
            number="02"
            title="Picking the right Hiking Gear!"
            subtitle="Hiking Essentials"
            content="The nice thing about beginning hiking is that you don't really need any special gear, you can probably get away with things you already have. Let's start with clothing. A typical mistake hiking beginners make is wearing jeans and regular clothes, which will get heavy and chafe wif they get sweaty or wet."
            imageSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/d61297f7b0d513bea9d2f5cb7495a99fe53406e1829f74858af95ac401ecf3b1?apiKey=3d455ab335804543820e9aded0b16cbd&"
            imageLeft={true}
          />
          <HikingSection
            number="03"
            title="Understand Your Map & Timing"
            subtitle="where you go is the key"
            content="To start, print out the hiking guide and map. If it's raining, throw them in a Zip-Lock bag. Read over the guide, study the map, and have a good idea of what to expect. I like to know what my next landmark is as I hike. For example, I'll read the guide and know that say, in a mile, I make a right turn at the junction."
            imageSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/c72582c8d36ce6d87747d64575978bfbf60c32fcfbcf72daac70bfe552f442f3?apiKey=3d455ab335804543820e9aded0b16cbd&"
          />
        </main>
        <Footer />
      </div>
    </div>
  );
};

export default HikingGuide;
