/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface HikingSectionProps {
  number: string;
  title: string;
  subtitle: string;
  content: string;
  imageSrc: string;
  imageLeft?: boolean;
}

const HikingSection: React.FC<HikingSectionProps> = ({
  number,
  title,
  subtitle,
  content,
  imageSrc,
  imageLeft = false,
}) => {
  const textContent = (
    <div className="flex flex-col w-[58%] max-md:ml-0 max-md:w-full">
      <div className="mt-10 max-md:mt-10 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <div className="flex flex-col w-[28%] max-md:ml-0 max-md:w-full">
            <div className="mr-0 font-bold leading-none text-white text-[240px] max-md:text-4xl">
              {number}
            </div>
          </div>
          <div className="flex flex-col ml-5 w-[72%] max-md:ml-0 max-md:w-full">
            <div className="flex overflow-hidden flex-col mt-24 w-full text-lg font-bold text-amber-200 max-md:mt-10 max-md:max-w-full">
              <div className="flex gap-5 max-w-full font-extrabold uppercase tracking-[6px] w-[268px]">
                <div className="flex shrink-0 my-auto h-0.5 bg-amber-200 w-[72px]" />
                <div className="flex-auto">{subtitle}</div>
              </div>
              <h2 className="mt-7 text-6xl font-semibold text-white max-md:max-w-full max-md:text-4xl">
                {title}
              </h2>
              <p className="mt-7 leading-8 text-white max-md:max-w-full">
                {content}
              </p>
              <div className="flex relative flex-col mt-7 max-w-full aspect-[5.773] w-[127px] max-md:pr-5">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/6dd5f98f4f67f6902ce5030fd89d4698681c89a8ce3a0348e8e42d0f29c485d2?apiKey=3d455ab335804543820e9aded0b16cbd&"
                  alt=""
                  className="object-cover absolute inset-0 size-full"
                />
                read more
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );

  const imageContent = (
    <div className="flex flex-col ml-5 w-[42%] max-md:ml-0 max-md:w-full">
      <img
        loading="lazy"
        src={imageSrc}
        alt=""
        className="object-contain grow w-full aspect-[0.79] max-md:mt-10 max-md:max-w-full"
      />
    </div>
  );

  return (
    <section className="w-full max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        {imageLeft ? imageContent : textContent}
        {imageLeft ? textContent : imageContent}
      </div>
    </section>
  );
};

export default HikingSection;
