/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface AppointmentProps {
  time: string;
  title: string;
  doctor: string;
}

const Appointment: React.FC<AppointmentProps> = ({ time, title, doctor }) => (
  <>
    <div className="flex gap-5 justify-between mr-7 ml-7 text-sm leading-4 text-neutral-400 max-md:mx-2.5">
      <div className="flex gap-2.5 my-auto">
        <div className="shrink-0 rounded-full bg-neutral-400 h-[11px] w-[11px]" />
        <div className="flex-auto">{time}</div>
      </div>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/f8b3dbdcbe87e3e626a3a9e22b59e31855206b4c7e038fa068cebb421818c81d?apiKey=3d455ab335804543820e9aded0b16cbd&&apiKey=3d455ab335804543820e9aded0b16cbd"
        className="shrink-0 w-6 aspect-square"
        alt=""
      />
    </div>
    <div className="self-start mt-6 ml-11 text-sm font-medium text-zinc-900 max-md:ml-2.5">
      {title}
    </div>
    <div className="self-start mt-5 ml-11 text-sm text-neutral-400 max-md:ml-2.5">
      {doctor}
    </div>
    <div className="shrink-0 mt-7 h-px bg-gray-200 border border-gray-200 border-solid" />
  </>
);

const AppointmentSection: React.FC = () => {
  const appointments = [
    {
      time: "08:30 am - 10:30 am",
      title: "Nurse Visit 20",
      doctor: "Dr. Carol D. Pollack-rundle",
    },
    {
      time: "08:30 am - 10:30 am",
      title: "Annual Visit 15",
      doctor: "Dr. Donald F. Watren",
    },
  ];

  return (
    <section>
      <div className="shrink-0 mt-8 h-px bg-gray-200 border border-gray-200 border-solid" />
      <div className="flex gap-5 px-px mt-9 text-lg font-medium text-neutral-600">
        <h2 className="flex-auto">Upcoming Appointment</h2>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/2586972d2bb7dd36f8bf04c19aa1d6b8602795e520ee7dc07ef71315652d97fe?apiKey=3d455ab335804543820e9aded0b16cbd&&apiKey=3d455ab335804543820e9aded0b16cbd"
          className="shrink-0 w-6 aspect-square"
          alt=""
        />
      </div>
      <div className="flex gap-5 justify-between mt-9 text-base leading-4 text-blue-600">
        <time dateTime="2022-07-30">July 30, 2022</time>
        <div className="shrink-0 my-auto h-px bg-blue-600 border border-blue-600 border-solid w-[228px]" />
      </div>
      {appointments.map((appointment, index) => (
        <Appointment key={index} {...appointment} />
      ))}
    </section>
  );
};

export default AppointmentSection;
