/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ProfileHeader from "./ProfileHeader.tsx";
import StatisticsSection from "./StatisticsSection.tsx";
import AppointmentSection from "./AppointmentSection.tsx";
import PatientSatisfaction from "./PatientSatisfaction.tsx";

const DoctorDashboard: React.FC = () => {
  return (
    <main className="flex flex-col grow px-5 py-16 mx-auto w-full bg-white border-l border-gray-200">
      <ProfileHeader />
      <StatisticsSection />
      <AppointmentSection />
      <PatientSatisfaction />
    </main>
  );
};

export default DoctorDashboard;
