/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface SatisfactionItemProps {
  color: string;
  label: string;
}

const SatisfactionItem: React.FC<SatisfactionItemProps> = ({
  color,
  label,
}) => (
  <div className="flex gap-5">
    <div className={`shrink-0 self-start w-2.5 h-2.5 ${color} rounded-sm`} />
    <div className="flex-auto">{label}</div>
  </div>
);

const PatientSatisfaction: React.FC = () => {
  const satisfactionItems = [
    { color: "bg-blue-600", label: "Excellent" },
    { color: "bg-orange-400", label: "Good" },
    { color: "bg-green-600", label: "Poor" },
  ];

  return (
    <section>
      <h2 className="mt-10 text-lg font-medium text-neutral-600">
        Patient Satisfaction
      </h2>
      <div className="flex gap-5 justify-between mt-10 text-sm whitespace-nowrap text-stone-500">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/f344eee2ae4425eb90dbac13a46f352c4e01cb50033b239ce803ff1aeb6057b4?apiKey=3d455ab335804543820e9aded0b16cbd&&apiKey=3d455ab335804543820e9aded0b16cbd"
          className="shrink-0 max-w-full rounded-md aspect-square w-[162px]"
          alt="Patient satisfaction chart"
        />
        <div className="flex flex-col my-auto">
          {satisfactionItems.map((item, index) => (
            <React.Fragment key={item.label}>
              {index > 0 && <div className="mt-11 max-md:mt-10" />}
              <SatisfactionItem {...item} />
            </React.Fragment>
          ))}
        </div>
      </div>
    </section>
  );
};

export default PatientSatisfaction;
