/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ProfileHeader: React.FC = () => {
  return (
    <>
      <div className="shrink-0 self-center w-20 h-20 bg-indigo-50 rounded-sm" />
      <h1 className="self-center mt-8 text-lg font-medium text-center text-zinc-900">
        Dr. Dilip Anmangandla, MD
      </h1>
    </>
  );
};

export default ProfileHeader;
