/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface StatItemProps {
  label: string;
  value: string | number;
}

const StatItem: React.FC<StatItemProps> = ({ label, value }) => (
  <div className="flex flex-col text-center whitespace-nowrap">
    <div className="text-xs text-neutral-400">{label}</div>
    <div className="mt-7 text-xl font-medium text-zinc-900">{value}</div>
  </div>
);

const StatisticsSection: React.FC = () => {
  return (
    <section className="flex gap-5 mt-10 w-full">
      <div className="flex flex-auto gap-5 justify-between">
        <StatItem label="Appointment" value={4250} />
        <div className="shrink-0 w-px bg-gray-200 border border-gray-200 border-solid h-[53px]" />
        <StatItem label="Total Patients" value="32.1k" />
        <div className="shrink-0 bg-gray-200 border border-gray-200 border-solid h-[53px] w-[23px]" />
      </div>
      <StatItem label="Rate" value={4.8} />
    </section>
  );
};

export default StatisticsSection;
