/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface SidebarItemProps {
  icon: string;
  label: string;
  isActive?: boolean;
}

const SidebarItem: React.FC<SidebarItemProps> = ({ icon, label, isActive }) => {
  return (
    <div
      className={`flex gap-5 pb-2 mt-8 max-w-full text-sm whitespace-nowrap w-[166px] ${
        isActive ? "text-white" : "text-neutral-400"
      }`}
    >
      <img
        loading="lazy"
        src={icon}
        className="shrink-0 self-start w-6 aspect-square"
        alt=""
      />
      <div>{label}</div>
    </div>
  );
};

export default SidebarItem;
