/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SidebarItem from "./SidebarItem.tsx";
import UserProfile from "./UserProfile.tsx";

interface SidebarProps {
  items: Array<{
    icon: string;
    label: string;
    isActive?: boolean;
  }>;
}

const Sidebar: React.FC<SidebarProps> = ({ items }) => {
  return (
    <nav className="flex flex-col grow items-center px-5 py-10 mx-auto w-full bg-white border-r border-gray-200">
      <header className="flex gap-4 text-xl font-semibold text-stone-500">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/0cc4adac8d27ddf2ef90bf56f1c190d172ee1d49cee75efa4c86c11c63e89e17?apiKey=3d455ab335804543820e9aded0b16cbd&&apiKey=3d455ab335804543820e9aded0b16cbd"
          className="shrink-0 w-8 rounded-none aspect-square"
          alt=""
        />
        <div className="flex-auto">
          <span className="text-blue-600">Happy</span>care
        </div>
      </header>
      <div className="shrink-0 self-stretch mt-14 bg-blue-600 rounded-sm shadow-2xl h-[42px] max-md:mt-10" />
      {items.map((item, index) => (
        <SidebarItem key={index} {...item} />
      ))}
      <UserProfile />
    </nav>
  );
};

export default Sidebar;
