/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Sidebar from "./Sidebar.tsx";

const sidebarItems = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/a09372bdc8106d4046239ee5f83dd7e96f052c42c1d9d984dd6d7ae1cc3e6020?apiKey=3d455ab335804543820e9aded0b16cbd&&apiKey=3d455ab335804543820e9aded0b16cbd",
    label: "Dashboard",
    isActive: true,
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/b28db21e869c5d622d9ad41160fcf58ae0221055966921fa521d1bc50be1efef?apiKey=3d455ab335804543820e9aded0b16cbd&&apiKey=3d455ab335804543820e9aded0b16cbd",
    label: "Appointment",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/526c1c3af9bd39780d11d8c84350ca45dbb5fa46b245b93ba18f77552aefea6d?apiKey=3d455ab335804543820e9aded0b16cbd&&apiKey=3d455ab335804543820e9aded0b16cbd",
    label: "Doctor",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/e958d38751d7033341d37d596d2a5075b22dbe802f0db1f50dc6397bf3e59e32?apiKey=3d455ab335804543820e9aded0b16cbd&&apiKey=3d455ab335804543820e9aded0b16cbd",
    label: "Patient",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/193b81878be1e226b0ffb5bcd9c27044c1c713e247f4db4527b2bcdfbc7c69f0?apiKey=3d455ab335804543820e9aded0b16cbd&&apiKey=3d455ab335804543820e9aded0b16cbd",
    label: "Report",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/3021b7c4266cd765ced5e13abf7d83af7470b34c9753f1d3e4e5ff9434d62961?apiKey=3d455ab335804543820e9aded0b16cbd&&apiKey=3d455ab335804543820e9aded0b16cbd",
    label: "Setting",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/da50a8b8750a5a6aba8c90f0bf3372d71e42f4821dc85486503e33a3b390db24?apiKey=3d455ab335804543820e9aded0b16cbd&&apiKey=3d455ab335804543820e9aded0b16cbd",
    label: "Logout",
  },
];

const SidebarContainer: React.FC = () => {
  return <Sidebar items={sidebarItems} />;
};

export default SidebarContainer;
