/**
 * This code was generated by Builder.io.
 */
import React from "react";

const UserProfile: React.FC = () => {
  return (
    <div className="flex gap-5 justify-between self-stretch mt-96 max-md:mt-10">
      <div className="flex gap-2.5">
        <div className="shrink-0 w-10 h-10 bg-indigo-50 rounded-sm" />
        <div className="flex flex-col my-auto">
          <div className="text-sm font-semibold text-right text-zinc-900">
            Eleanor Pena
          </div>
          <div className="mt-3.5 text-xs text-neutral-400">Doctor</div>
        </div>
      </div>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/1de6412e17827377afbdd8d4cd674331e88cbe7a67ea775191dbcfab728e5193?apiKey=3d455ab335804543820e9aded0b16cbd&&apiKey=3d455ab335804543820e9aded0b16cbd"
        className="shrink-0 my-auto w-6 aspect-square"
        alt=""
      />
    </div>
  );
};

export default UserProfile;
